"""
ShufaClaw V2 — Agent & Report Schemas

Schemas for AI agent orchestration and their reports.
"""

from datetime import datetime
from typing import Optional
from uuid import UUID, uuid4
from enum import Enum
from pydantic import BaseModel, Field


class AgentType(str, Enum):
    """Types of AI agents in the system."""
    MARKET_ANALYST = "market_analyst"
    STRATEGY_RESEARCH = "strategy_research"
    PERFORMANCE_ANALYST = "performance_analyst"
    RISK_REVIEW = "risk_review"
    REGIME_ADAPTATION = "regime_adaptation"


class AgentPriority(str, Enum):
    """Agent execution priority."""
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"       # RiskReview, RegimeAdaptation
    CRITICAL = "critical"


class AgentReport(BaseModel):
    """
    A report generated by an AI agent after running its analysis.
    Reports are stored permanently and never deleted.
    """
    id: UUID = Field(default_factory=uuid4)
    agent_type: AgentType
    trigger: str = Field(..., description="What caused this agent to run, e.g. 'scheduled_4h', 'regime_change'")
    priority: AgentPriority = AgentPriority.NORMAL

    # Report content
    summary: str = Field(..., description="Short one-line summary")
    analysis: str = Field(..., description="Full analysis text")
    recommendations: list[str] = Field(default_factory=list, description="Actionable recommendations")
    data_snapshot: dict = Field(default_factory=dict, description="Key data at time of analysis")

    # Metadata
    execution_time_seconds: float = 0.0
    tokens_used: int = 0
    model_used: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)
